server:
  port: 9081
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
  provider:
    timeout: 1000
provider123:
    service:
      version : 1.0.0

spring:
  application:
    name: dubbo-provider
  datasource:
#    url: jdbc:mysql://192.168.66.60:3306/pandora_dev?useUnicode=true&amp;characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/pandora_dev?useUnicode=true&amp;characterEncoding=utf-8

    username: root
#    password: root123
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
      batch_size: 0
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

